title: Build a line follower
hero_image: images/banner.png
description: rpi-python-line-following description
theme: red # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 3
version: 4
listed: false
ingredient: false
copyedit: false
last_tested: "2018-04-10"
curriculum: 3, design-0, programming-3, phys-comp-3, manufacture-2, community-0
interests: "robotics"
technologies: "electronic-components, raspberry-pi, python"
hardware: "electronic-components, raspberry-pi"
software: "python"
site_areas: projects
steps:
  - title: Introduction
  - title: Preparing the connectors
  - title: Connecting the line sensors
  - title: Test the lines sensors
  - title: Programming a line following algorithm
  - title: Planning a better algorithm
  - title: The final algorithm
  
